server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/backmanagement?useSSL=false
        username: root
        password: root
        # user druid datasource
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
    rabbitmq:
        virtual-host: /
        username: root
        password: root
        addresses: 127.0.0.1:5672
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        pool.max-active: 8
        pool.max-wait: -1
        pool.max-idle: 8
        pool.min-idle: 0
        timeout: 0


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.pojo

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
